version: '3.9'
services:
  postgres:
    container_name: postgres_
    image: postgres:13.3
    environment:
      POSTGRES_DB: "yeetcross"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pQmuvPsT7r"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d jumys" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  mongo:
    container_name: mongo_
    restart: always
    logging:
        options:
          max-size: 1g
    image: mongo
